name: CI/CD for Streamlit App

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run basic tests
        run: |
          python -m py_compile loan_default_app.py
          echo "✅ App syntax looks good"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Streamlit Cloud Deployment
        run: echo "🚀 Streamlit redeploys automatically when repo updates"

